FROM alpine:20210804

RUN apk add \
    neovim \
    neovim-doc \
    llvm12 \
    clang \
    clang-analyzer \
    clang-extra-tools \
    clang-doc \
    lldb \
    cmake \
    cmake-doc \
    samurai \
    samurai-doc \
    git \
    git-doc \
    curl \
    curl-doc \
    ncurses \
    ncurses-terminfo \
    ncurses-doc
